### PR TITLE
lightweight random greedy optimization

### PR DESCRIPTION
**Pull request by jcmgray**
This adds support for lightweight random greedy optimization (no hyper parameter tuning or ContractionTree construction), with the following:

- `optimize_random_greedy_track_flops`, with a cotengrust version to follow.
- `RandomGreedyOptimizer`, a stateful optimizer which wraps the python or rust version above, with parallelization etc.

TODO:

- [ ] maybe a `ReusableRandomGreedyOptimizer`

cc @CSNWEB

### CODE REVIEW

**Comment by CSNWEB** [comment]
Awesome that was fast, thanks! I will have a look at it later this week.

**Comment by jcmgray** [comment]
Rust counterpart is here: https://github.com/jcmgray/cotengrust/commit/f3a3e504212d2969037960bbdfb98979c82656a5.

With the overall performance increase (and memory decrease), pretty big contractions are now amenable:

```python
import cotengra as ctg

# 10,000 nodes
inputs, output, shapes, size_dict = ctg.utils.lattice_equation([100, 100])
opt = ctg.RandomGreedyOptimizer(max_repeats=128)

%%timeit
ssa_path = opt.ssa_path(inputs, output, size_dict)
# 1.75 s ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by jcmgray** [comment]
Merging for the moment, but open to any additional suggestions before releasing it.

**Comment by CSNWEB** [comment]
Thanks again, looked through the code and it looks very good to me. Seems to contain everything I mentioned and could need.

**Pull request merged**
